language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: QXayLK3YPxzcK5WP9hKg5XE8deYc892ub4APosJtt9/+2zEDMBAom4088HvbyxS3HJhgrNR3a8JEU464U6V0raiLRWP6mk/4gB3PnJ4BB/mvBpoJT4+DWzUG2GHgV5e9vngeSQUAjfafcsn/K4XVYn4eWhBpeDwiaHETo6JOLEA+bYWZugMZEe1TYrc3XwYLpf0Zw60U71vy2yWCz6Hhv+FaAYXtPQd9FCms1u9BRdRTNpwUuJsMPlE2H6ofcMYHCIqSzD+wkLJ784Rq89cEOjPa+iAFjsS3bEcyg7OPEf26rjUS0A8kFmt7+Ekf9KQJ0HTJc/GkcxQDLIDR7gBtp3paXPnrGjJPJpfU2Knhen7n+r5n29TGeaOBQkF6dg2R+B/y5CHal3/afwlWTsXC3KLiOxh3wIAbuHmRtmJoZxXarcQ/opvWBAr2PGEXAG8NHnrqU1MoVpbUylDyw+B1WhZTf6BEFzaPLkXo9ugKCROM0dXAWb+q+k2TqwK+WJZ1PIo01xgYq7pMa24JkjF3HhqE8yGw4P0VAoljhu2/BH1teByeQ02kEBx5SM3UKkqJWy7m/9x+QGNcvGhOXO0YiXw+sFvnm8bO+d+JFtS7ecy/KclLrppsTniRQ92flSn5Zr4k+vlHNSSJVbikx3HSrtrxUUTOXPELfAsbVJ2R80I=
  app: ist-calc
